=== miguelfrdnz/DTD-lll/DTD_lll.dtd
<!ELEMENT cuento (personajes, trama, etiqueta*, precio?)>
<!ATTLIST cuento cod ID #REQUIRED
                  título CDATA #REQUIRED
                  género (infantil | fantasía | terror) #IMPLIED>

<!ELEMENT personajes (personaje+)>
<!ELEMENT personaje (nombre, género, descripción?, (descripción_fisica | imagen | url)?)>
<!ATTLIST personaje id ID #REQUIRED
                    tipo (principal | secundario | antagonista) "principal">

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT género (#PCDATA)>
<!ELEMENT descripción (#PCDATA)>
<!ELEMENT descripción_fisica (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT url (#PCDATA)>

<!ELEMENT trama (#PCDATA)>
<!ELEMENT etiqueta EMPTY>
<!ATTLIST etiqueta nombre CDATA #REQUIRED>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA "eur">

=== miguelfrdnz/DTD-lll/DTD_lll_1.xml
<!DOCTYPE cuento SYSTEM "DTD_lll.dtd">
<cuento cod="A01" título="El Bosque Encantado" género="fantasía">
    <personajes>
        <personaje id="p1" tipo="principal">
            <nombre>Aldric</nombre>
            <género>M</género>
            <descripción>Un joven mago en busca de conocimiento.</descripción>
            <imagen>aldric.png</imagen>
        </personaje>
        <personaje id="p2" tipo="antagonista">
            <nombre>La Sombra</nombre>
            <género>N</género>
            <descripción>Una entidad oscura que acecha en la niebla.</descripción>
            <url>http://historiasdelbosque.com/lasombra</url>
        </personaje>
    </personajes>
    <trama>Aldric debe atravesar un bosque mágico lleno de desafíos y enfrentarse a la Sombra.</trama>
    <etiqueta nombre="magia"/>
    <etiqueta nombre="aventura"/>
    <precio moneda="usd">12.99</precio>
</cuento>

=== miguelfrdnz/DTD-lll/DTD_lll_2.xml
<!DOCTYPE cuento SYSTEM "DTD_lll.dtd">
<cuento cod="B02" título="El Susurro de la Noche" género="terror">
    <personajes>
        <personaje id="p1" tipo="principal">
            <nombre>Lucía</nombre>
            <género>F</género>
            <descripción>Una niña curiosa que oye voces en la oscuridad.</descripción>
            <descripción_fisica>Cabello oscuro y ojos grandes.</descripción_fisica>
        </personaje>
        <personaje id="p2" tipo="secundario">
            <nombre>Abuela Marta</nombre>
            <género>F</género>
            <descripción>Una anciana sabia que conoce los secretos del pueblo.</descripción>
            <imagen>abuela_marta.jpg</imagen>
        </personaje>
    </personajes>
    <trama>Lucía descubre que las voces que oye en la noche provienen de los espíritus atrapados en su casa.</trama>
    <etiqueta nombre="misterio"/>
    <etiqueta nombre="espíritus"/>
</cuento>
